### ISSUE TITLE
CI is broken so PRs cannot go through

### ISSUE THREAD

**Issue by aappddeevv** [reactjs/reactjs.org#946]
The error seems the same across multiple PRs:
```sh
#!/bin/bash -eo pipefail
yarn install
yarn install v1.7.0
...elided...
[5/5] Building fresh packages...
error /home/circleci/project/node_modules/sharp: Command failed.
Exit code: 1
Command: node-gyp rebuild
```

**Comment by gaearon** [comment]
Yeah. Can you look into what’s happening there?

**Comment by gaearon** [comment]
Thanks!

**Comment by gaearon** [comment]
This is happening again.

**Comment by alexkrolick** [comment]
Is it possible to upgrade `yarn` on Netlify? It looks like it's on 0.18 which may be related.

**Comment by AlmeroSteyn** [comment]
I want to merge #923, but the Netlify build failed, which seems related. Do I need to wait for a fix here before doing so?

**Comment by alexkrolick** [comment]
Umm... well hard to say if it will build correctly if merged. Probably not...

Do we need the Sharp plugin? It optimizes images and as far as I can tell there are only a few in use, mostly in super old blogposts.

**Comment by AlmeroSteyn** [comment]
Hmmm and in the a11y doc.

The PR above is adding a few gifs for explanation.

**Comment by KyleAMathews** [comment]
Definitely try upgrading Yarn on Netlify https://www.netlify.com/docs/build-settings/#build-environment-variables

**Comment by KyleAMathews** [comment]
Removing gatsby-plugin-sharp will break the site build. Upgrading Yarn should fix installing it.

**Comment by alexkrolick** [comment]
Seems to be building ok on my fork when I set the YARN_VERSION env var to 1.7.0

https://app.netlify.com/sites/awesome-lamport-bc682b/deploys/5b45ad80792f897a0375023e

**Comment by AlmeroSteyn** [comment]
Stupid question time. Is there a way I can easily redeploy my PR to on Netlify to check? Or do I need to push a change?

**Comment by alexkrolick** [comment]
you could make a new branch off the old one and open a PR

**Comment by AlmeroSteyn** [comment]
Thanks!

But should this be fixed now? I saw your PR still unmerged though. I'm happy to wait if changes are still pending.

**Comment by alexkrolick** [comment]
it's not fixed - I think Kyle is right and changing the settings in Netflify to upgrade yarn is the real solution; anything in my PR is incidental

**Comment by alexkrolick** [comment]
Sure, plus we have to go update a bunch of other PRs

**Comment by alexkrolick** [comment]
@AlmeroSteyn should be good now 😄

**Comment by AlmeroSteyn** [comment]
Thank you!! Is there any action required on an existing PR or will it work just to merge it?

**Comment by alexkrolick** [comment]
Should just work, rebase if not

**Comment by AlmeroSteyn** [comment]
@alexkrolick I just rebased and pushed a small change and the Netlify build gave the same error again. I assume this is being handled further in #1058 .
